--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
name:         WWW-Domain-Registry-Joker
abstract:     An interface to the Joker.com DMAPI
version:      0.09
version_from: lib/WWW/Domain/Registry/Joker.pm
author:
    - Peter Pentchev <roam@ringlet.net>
license: perl
distribution_type: module
installdirs:  site
requires:
    Log::Dispatch:                 2
    LWP:                           5
    Test::More:                    0
build_requires:
    Test::Pod::Coverage:           0
resources:
    license: http://dev.perl.org/licenses/
meta_spec:
    version: 1.4
    url: http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: hand
