# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Domain-Registry-Joker
version:      0.05
version_from: lib/WWW/Domain/Registry/Joker.pm
installdirs:  site
requires:
    Log::Dispatch:                 2
    LWP:                           5
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
